services:
  kafka:
    image: apache/kafka:3.7.0
    environment:
      - CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    ports:
      - "9092:9092"
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  producer:
    build: .
    command: ["/app/producer"]
    restart: unless-stopped
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=events
      - EVENT_RATE=5
    depends_on:
      - kafka
  consumer:
    build: .
    command: ["/app/consumer"]
    restart: unless-stopped
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=events
      - KAFKA_GROUP_ID=event-consumers
      - MSSQL_CONN=sqlserver://sa:YourStrong!Passw0rd@mssql:1433?database=events&encrypt=disable
      - REDIS_ADDR=redis:6379
      - DLQ_LIST=dlq
      - METRICS_ADDR=:2112
    ports:
      - "2112:2112"
    depends_on:
      - kafka
      - mssql
      - redis
  api:
    build: .
    command: ["/app/api"]
    environment:
      - MSSQL_CONN=sqlserver://sa:YourStrong!Passw0rd@mssql:1433?database=events&encrypt=disable
      - API_ADDR=:8080
      - METRICS_ADDR=:2113
    ports:
      - "8080:8080"
      - "2113:2113"
    depends_on:
      - mssql
